apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1  # Number of instances of your application
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: mohammedhomman/medhomman-portfolio:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 80  # The port your container listens on
