apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
  - protocol: TCP
    port: 80         # The port exposed by the service
    targetPort: 80   # The port in the container (same as containerPort in deployment.yaml)
  type: LoadBalancer
